// Generated by miqt-uic. To update this file, edit the .ui file in
// Qt Designer, and then run 'go generate'.
//
//go:generate miqt-uic -Qt6 -InFile QT_windows/main.ui -OutFile ui_main.go -Package main

package main

import (
	qt "github.com/mappu/miqt/qt6"
)

type MainWindowUi struct {
	MainWindow       *qt.QMainWindow
	centralwidget    *qt.QWidget
	gridLayoutWidget *qt.QWidget
	gridLayout       *qt.QGridLayout
	label_3          *qt.QLabel
	label            *qt.QLabel
	album_search     *qt.QLineEdit
	artist_search    *qt.QLineEdit
	label_2          *qt.QLabel
	songs_list       *qt.QListWidget
	artists_list     *qt.QListWidget
	song_search      *qt.QLineEdit
	albums_list      *qt.QListWidget
	warning_label    *qt.QLabel
	formLayout       *qt.QFormLayout
	label_4          *qt.QLabel
	label_5          *qt.QLabel
	label_6          *qt.QLabel
	play_stop_button *qt.QPushButton
	song_slider      *qt.QSlider
	record_label     *qt.QLabel
	artist_label     *qt.QLabel
	name_label       *qt.QLabel
	menubar          *qt.QMenuBar
	statusbar        *qt.QStatusBar
}

// NewMainWindowUi creates all Qt widget classes for MainWindow.
func NewMainWindowUi() *MainWindowUi {
	ui := &MainWindowUi{}
	ui.MainWindow = qt.NewQMainWindow(nil)
	MainWindow__objectName := qt.NewQAnyStringView3("MainWindow")
	ui.MainWindow.SetObjectName(*MainWindow__objectName)
	MainWindow__objectName.Delete() // setter copied value
	ui.MainWindow.Resize(585, 596)
	ui.centralwidget = qt.NewQWidget(ui.MainWindow.QWidget)
	centralwidget__objectName := qt.NewQAnyStringView3("centralwidget")
	ui.centralwidget.SetObjectName(*centralwidget__objectName)
	centralwidget__objectName.Delete() // setter copied value
	ui.gridLayoutWidget = qt.NewQWidget(ui.centralwidget)
	gridLayoutWidget__objectName := qt.NewQAnyStringView3("gridLayoutWidget")
	ui.gridLayoutWidget.SetObjectName(*gridLayoutWidget__objectName)
	gridLayoutWidget__objectName.Delete() // setter copied value
	ui.gridLayoutWidget.SetGeometry(30, 0, 532, 508)
	ui.gridLayout = qt.NewQGridLayout(ui.gridLayoutWidget)
	gridLayout__objectName := qt.NewQAnyStringView3("gridLayout")
	ui.gridLayout.SetObjectName(*gridLayout__objectName)
	gridLayout__objectName.Delete() // setter copied value
	ui.gridLayout.SetContentsMargins(11, 11, 11, 11)
	ui.gridLayout.SetSpacing(6)
	ui.label_3 = qt.NewQLabel(ui.gridLayoutWidget)
	label_3__objectName := qt.NewQAnyStringView3("label_3")
	ui.label_3.SetObjectName(*label_3__objectName)
	label_3__objectName.Delete() // setter copied value
	ui.label_3.SetAlignment(qt.AlignCenter)

	ui.gridLayout.AddWidget3(ui.label_3.QWidget, 5, 1, 1, 2)
	ui.label = qt.NewQLabel(ui.gridLayoutWidget)
	label__objectName := qt.NewQAnyStringView3("label")
	ui.label.SetObjectName(*label__objectName)
	label__objectName.Delete() // setter copied value
	ui.label.SetAlignment(qt.AlignCenter)

	ui.gridLayout.AddWidget2(ui.label.QWidget, 1, 1)
	ui.album_search = qt.NewQLineEdit(ui.gridLayoutWidget)
	album_search__objectName := qt.NewQAnyStringView3("album_search")
	ui.album_search.SetObjectName(*album_search__objectName)
	album_search__objectName.Delete() // setter copied value

	ui.gridLayout.AddWidget2(ui.album_search.QWidget, 2, 2)
	ui.artist_search = qt.NewQLineEdit(ui.gridLayoutWidget)
	artist_search__objectName := qt.NewQAnyStringView3("artist_search")
	ui.artist_search.SetObjectName(*artist_search__objectName)
	artist_search__objectName.Delete() // setter copied value

	ui.gridLayout.AddWidget2(ui.artist_search.QWidget, 2, 1)
	ui.label_2 = qt.NewQLabel(ui.gridLayoutWidget)
	label_2__objectName := qt.NewQAnyStringView3("label_2")
	ui.label_2.SetObjectName(*label_2__objectName)
	label_2__objectName.Delete() // setter copied value
	ui.label_2.SetAlignment(qt.AlignCenter)

	ui.gridLayout.AddWidget2(ui.label_2.QWidget, 1, 2)
	ui.songs_list = qt.NewQListWidget(ui.gridLayoutWidget)
	songs_list__objectName := qt.NewQAnyStringView3("songs_list")
	ui.songs_list.SetObjectName(*songs_list__objectName)
	songs_list__objectName.Delete() // setter copied value

	ui.gridLayout.AddWidget2(ui.songs_list.QWidget, 7, 1)
	ui.artists_list = qt.NewQListWidget(ui.gridLayoutWidget)
	artists_list__objectName := qt.NewQAnyStringView3("artists_list")
	ui.artists_list.SetObjectName(*artists_list__objectName)
	artists_list__objectName.Delete() // setter copied value

	ui.gridLayout.AddWidget2(ui.artists_list.QWidget, 3, 1)
	ui.song_search = qt.NewQLineEdit(ui.gridLayoutWidget)
	song_search__objectName := qt.NewQAnyStringView3("song_search")
	ui.song_search.SetObjectName(*song_search__objectName)
	song_search__objectName.Delete() // setter copied value

	ui.gridLayout.AddWidget2(ui.song_search.QWidget, 6, 1)
	ui.albums_list = qt.NewQListWidget(ui.gridLayoutWidget)
	albums_list__objectName := qt.NewQAnyStringView3("albums_list")
	ui.albums_list.SetObjectName(*albums_list__objectName)
	albums_list__objectName.Delete() // setter copied value

	ui.gridLayout.AddWidget2(ui.albums_list.QWidget, 3, 2)
	ui.warning_label = qt.NewQLabel(ui.gridLayoutWidget)
	warning_label__objectName := qt.NewQAnyStringView3("warning_label")
	ui.warning_label.SetObjectName(*warning_label__objectName)
	warning_label__objectName.Delete() // setter copied value
	ui.warning_label.SetStyleSheet("color:red")

	ui.gridLayout.AddWidget3(ui.warning_label.QWidget, 0, 1, 1, 2)
	ui.formLayout = qt.NewQFormLayout2()
	formLayout__objectName := qt.NewQAnyStringView3("formLayout")
	ui.formLayout.SetObjectName(*formLayout__objectName)
	formLayout__objectName.Delete() // setter copied value
	ui.formLayout.SetContentsMargins(0, 0, 0, 0)
	ui.formLayout.SetSpacing(6)
	ui.label_4 = qt.NewQLabel(ui.gridLayoutWidget)
	label_4__objectName := qt.NewQAnyStringView3("label_4")
	ui.label_4.SetObjectName(*label_4__objectName)
	label_4__objectName.Delete() // setter copied value

	ui.formLayout.SetWidget(0, qt.QFormLayout__LabelRole, ui.label_4.QWidget)
	ui.label_5 = qt.NewQLabel(ui.gridLayoutWidget)
	label_5__objectName := qt.NewQAnyStringView3("label_5")
	ui.label_5.SetObjectName(*label_5__objectName)
	label_5__objectName.Delete() // setter copied value

	ui.formLayout.SetWidget(2, qt.QFormLayout__LabelRole, ui.label_5.QWidget)
	ui.label_6 = qt.NewQLabel(ui.gridLayoutWidget)
	label_6__objectName := qt.NewQAnyStringView3("label_6")
	ui.label_6.SetObjectName(*label_6__objectName)
	label_6__objectName.Delete() // setter copied value

	ui.formLayout.SetWidget(4, qt.QFormLayout__LabelRole, ui.label_6.QWidget)
	ui.play_stop_button = qt.NewQPushButton(ui.gridLayoutWidget)
	play_stop_button__objectName := qt.NewQAnyStringView3("play_stop_button")
	ui.play_stop_button.SetObjectName(*play_stop_button__objectName)
	play_stop_button__objectName.Delete() // setter copied value
	ui.play_stop_button.SetStyleSheet("")

	ui.formLayout.SetWidget(5, qt.QFormLayout__FieldRole, ui.play_stop_button.QWidget)
	ui.song_slider = qt.NewQSlider(ui.gridLayoutWidget)
	song_slider__objectName := qt.NewQAnyStringView3("song_slider")
	ui.song_slider.SetObjectName(*song_slider__objectName)
	song_slider__objectName.Delete() // setter copied value
	ui.song_slider.SetEnabled(true)
	ui.song_slider.SetOrientation(qt.Horizontal)
	ui.song_slider.SetTickInterval(1)

	ui.formLayout.SetWidget(6, qt.QFormLayout__LabelRole, ui.song_slider.QWidget)
	ui.record_label = qt.NewQLabel(ui.gridLayoutWidget)
	record_label__objectName := qt.NewQAnyStringView3("record_label")
	ui.record_label.SetObjectName(*record_label__objectName)
	record_label__objectName.Delete() // setter copied value
	ui.record_label.SetAutoFillBackground(false)

	ui.formLayout.SetWidget(4, qt.QFormLayout__FieldRole, ui.record_label.QWidget)
	ui.artist_label = qt.NewQLabel(ui.gridLayoutWidget)
	artist_label__objectName := qt.NewQAnyStringView3("artist_label")
	ui.artist_label.SetObjectName(*artist_label__objectName)
	artist_label__objectName.Delete() // setter copied value
	ui.artist_label.SetAutoFillBackground(false)

	ui.formLayout.SetWidget(2, qt.QFormLayout__FieldRole, ui.artist_label.QWidget)
	ui.name_label = qt.NewQLabel(ui.gridLayoutWidget)
	name_label__objectName := qt.NewQAnyStringView3("name_label")
	ui.name_label.SetObjectName(*name_label__objectName)
	name_label__objectName.Delete() // setter copied value
	ui.name_label.SetEnabled(true)
	ui.name_label.SetAutoFillBackground(false)

	ui.formLayout.SetWidget(0, qt.QFormLayout__FieldRole, ui.name_label.QWidget)

	ui.gridLayout.AddLayout2(ui.formLayout.QLayout, 6, 2, 2, 1)
	ui.MainWindow.SetCentralWidget(ui.centralwidget) // Set central widget
	ui.menubar = qt.NewQMenuBar(ui.MainWindow.QWidget)
	menubar__objectName := qt.NewQAnyStringView3("menubar")
	ui.menubar.SetObjectName(*menubar__objectName)
	menubar__objectName.Delete() // setter copied value
	ui.menubar.Resize(585, 37)
	ui.MainWindow.SetMenuBar(ui.menubar)
	ui.statusbar = qt.NewQStatusBar(ui.MainWindow.QWidget)
	statusbar__objectName := qt.NewQAnyStringView3("statusbar")
	ui.statusbar.SetObjectName(*statusbar__objectName)
	statusbar__objectName.Delete() // setter copied value
	ui.MainWindow.SetStatusBar(ui.statusbar)

	ui.Retranslate()

	return ui
}

// Retranslate reapplies all text translations.
func (ui *MainWindowUi) Retranslate() {
	ui.MainWindow.SetWindowTitle(qt.QCoreApplication_Tr("Другая опера"))
	ui.label_3.SetText(qt.QWidget_Tr("Песни"))
	ui.label.SetText(qt.QWidget_Tr("Артист"))
	ui.album_search.SetPlaceholderText(qt.QWidget_Tr("Поиск по альбомам"))
	ui.artist_search.SetPlaceholderText(qt.QWidget_Tr("Поиск по артистам"))
	ui.label_2.SetText(qt.QWidget_Tr("Альбом"))
	ui.song_search.SetPlaceholderText(qt.QWidget_Tr("Поиск по песням"))
	ui.warning_label.SetText(qt.QWidget_Tr(""))
	ui.label_4.SetText(qt.QWidget_Tr("Название:"))
	ui.label_5.SetText(qt.QWidget_Tr("Артист:"))
	ui.label_6.SetText(qt.QWidget_Tr("Альбом"))
	ui.play_stop_button.SetText(qt.QWidget_Tr("PLAY"))
	ui.record_label.SetText(qt.QWidget_Tr(""))
	ui.artist_label.SetText(qt.QWidget_Tr(""))
	ui.name_label.SetText(qt.QWidget_Tr(""))
}
